/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class create */

#ifndef _Included_create
#define _Included_create
#ifdef __cplusplus
extern "C" {
#endif
#undef create_serialVersionUID
#define create_serialVersionUID 1i64
#undef create_serialVersionUID
#define create_serialVersionUID 1i64
/*
 * Class:     create
 * Method:    add
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;III)I
 */
JNIEXPORT jint JNICALL Java_create_add
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
